name: Asciidoctor

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install asciidoctor-pdf
        run: gem install asciidoctor-pdf

      - run: asciidoctor-pdf presentacion.adoc -o presentacion.pdf
        working-directory: ./
