name: Asciidoctor

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - run: git clone -b 4.1.2 --depth 1 https://github.com/hakimel/reveal.js.git
        working-directory: ./

      - run: ./asciidoctor-revealjs --version
        working-directory: ./
