name: Asciidoctor

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - run: gem install asciidoctor-pdf

      - run: asciidoctor-pdf presentacion.adoc -o presentacion.pdf
        working-directory: ./
      - uses: actions/upload-artifact@v3
        with:
          path: ./presentacion.pdf
