name: Build AsciiDoc to reveal.js slides

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout el código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Descargar asciidoctor-revealjs Standalone Executable
      - name: Download asciidoctor-revealjs
        run: |
          wget https://github.com/asciidoctor/asciidoctor-reveal.js/releases/download/v5.1.0/asciidoctor-revealjs-linux
          chmod +x asciidoctor-revealjs-linux

      # Paso 3: Descargar reveal.js framework
      - name: Clone reveal.js
        run: |
          git clone -b 4.1.2 --depth 1 https://github.com/hakimel/reveal.js.git

      # Paso 4: Convertir archivo AsciiDoc a HTML usando asciidoctor-revealjs
      - name: Convert AsciiDoc to reveal.js slides
        run: |
          ./asciidoctor-revealjs-linux presentacion.adoc -o presentacion.html

      # Paso 5: Subir el archivo HTML generado como un artefacto
      - name: Upload HTML
        uses: actions/upload-artifact@v3
        with:
          name: presentacion-slides
          path: ./presencation.html
